name: Test build

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Test github actions 
        run: echo "Hello World!"
      - name: Testing out main directory
        run: pwd
      - name: Listing all directories
        run: tree . 
      - name: update submodules 
        run: git submodule sync && git submodule update --init
      - name: Create 'build' directory
        run: mkdir build
      - name: run cmake configuration
        run: cd build && cmake .. 
      - name: build project
        run: cd build && make

      