name: Test build

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Installing SUDO
        run: apt-get update && apt-get install -y sudo
      - name: Installing TZData
        run: DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
      - name: Installing X11 drivers
        run: export TZ="America/New_York" && export DEBIAN_FRONTEND="noninteractive" && apt-get update && sudo apt install -y xorg-dev libglu1-mesa mesa-opencl-icd libgl1-mesa-dev xsltproc libglfw3-dev libglu1-mesa-dev xvfb libxinerama1 libxcursor1
      - name: update submodules 
        run: git submodule sync && git submodule update --init
      - name: Create 'build' directory
        run: mkdir build
      - name: run cmake configuration
        run: cd build && cmake .. 
      - name: build project
        run: cd build && make

      