name: Test build

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Test github actions 
        run: echo "Hello World!"